# Generated by Django 5.2.6 on 2025-10-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.CharField(blank=True, choices=[('rpa', 'Robotic Process Automation (RPA)'), ('analytics', 'Data Analytics & Business Intelligence'), ('training', 'Professional Training & Certification'), ('accounting', 'Accounting & Business Filing Automation'), ('consultation', 'Strategic Automation Consultation'), ('other', 'Other Services')], max_length=20, null=True)),
                ('timeline', models.CharField(blank=True, choices=[('immediate', 'Immediately'), ('1-3months', 'Within 1-3 months'), ('3-6months', 'Within 3-6 months'), ('planning', 'Still planning')], max_length=20, null=True)),
                ('message', models.TextField()),
                ('newsletter', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
